# Generated by Django 5.0.2 on 2024-09-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_earned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='earned',
            new_name='balance',
        ),
    ]
