# Generated by Django 5.0.2 on 2024-09-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_task',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='usertasks',
            name='status',
            field=models.CharField(choices=[('pendingTasks', 'pendingTasks'), ('passedTasks', 'passedTasks'), ('failedTasks', 'failedTasks')], default='pendingTasks', max_length=15),
        ),
    ]
