# Generated by Django 5.0.2 on 2024-09-11 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_title_history_amount_alter_history_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='dates',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('pending debit', 'Pending Debit'), ('pending credit', 'Pending Credit')], default='pending debit', max_length=15),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.CharField(choices=[('Funds have been successfully withdrawn from your account as per your request for cash out or transfer.', 'Funds have been successfully withdrawn from your account as per your request for cash out or transfer.'), ('Earned money has been credited to your account from completed tasks or job payments.', 'Earned money has been credited to your account from completed tasks or job payments.'), ('Your request to withdraw funds is currently under review and is awaiting approval for processing.', 'Your request to withdraw funds is currently under review and is awaiting approval for processing.'), ('Credit for the tasks you’ve completed is pending and will be added to your account once reviewed.', 'Credit for the tasks you’ve completed is pending and will be added to your account once reviewed.')], default='Your request to withdraw funds is currently under review and is awaiting approval for processing.', max_length=200),
        ),
    ]
