# Generated by Django 5.0.2 on 2024-09-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasPaid',
            field=models.BooleanField(default=False),
        ),
    ]
