# Generated by Django 5.0.2 on 2024-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_haspaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasks',
            name='photo',
            field=models.ImageField(upload_to='User Tasks/'),
        ),
    ]
