# Generated by Django 5.0.2 on 2024-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_usertasks_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
