# Generated by Django 5.0.2 on 2024-09-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_documents_thefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='theFile',
            field=models.FileField(default=1, upload_to='Documents/'),
            preserve_default=False,
        ),
    ]
