# Generated by Django 5.0.2 on 2024-09-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_documents_thefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='is_downloaded',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='theFile',
        ),
        migrations.AddField(
            model_name='documents',
            name='govID',
            field=models.FileField(default=1, upload_to='Documents/Gov/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='stuID',
            field=models.FileField(default=1, upload_to='Documents/Student/'),
            preserve_default=False,
        ),
    ]
