# Generated by Django 5.0.2 on 2024-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_documents_is_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failTasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='passTasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pendTasks',
            field=models.IntegerField(default=0),
        ),
    ]
