# Generated by Django 5.0.2 on 2024-09-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_failtasks_user_passtasks_user_pendtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='status',
        ),
    ]
