# Generated by Django 5.0.2 on 2024-09-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_usertasks_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='PayOut',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='VerificationFee',
        ),
    ]
