# Generated by Django 5.0.2 on 2024-09-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_history_payout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='UserTasks',
            new_name='UserTask',
        ),
    ]
