# Generated by Django 5.0.2 on 2024-09-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_minwithdraw_user_rearns'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
