# Generated by Django 5.0.2 on 2024-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_banklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklist',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
