# Generated by Django 5.0.2 on 2024-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_banklist_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
