# Generated by Django 5.0.2 on 2024-09-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_banklist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
