# Generated by Django 5.0.2 on 2024-09-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_payout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='action',
            field=models.CharField(default='pending debit', max_length=15),
        ),
    ]
