# Generated by Django 5.0.2 on 2024-09-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_payout_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='action',
        ),
        migrations.AddField(
            model_name='payout',
            name='actions',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('pending debit', 'Pending Debit'), ('pending credit', 'Pending Credit')], default='pending debit', max_length=15),
        ),
    ]
