# Generated by Django 5.0.2 on 2024-09-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_payout_action_payout_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
