# Generated by Django 5.0.2 on 2024-09-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_payout_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='actions',
            new_name='action',
        ),
    ]
