# Generated by Django 5.0.2 on 2024-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_actions_payout_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='address',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payout',
            name='bankcode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
