# Generated by Django 5.0.2 on 2024-09-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_payout_address_payout_bankcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rearns',
            field=models.FloatField(default=0.3),
        ),
    ]
