# Generated by Django 5.0.2 on 2024-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_user_last_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_time',
        ),
        migrations.AddField(
            model_name='usertask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
