# Generated by Django 5.0.2 on 2024-09-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='earned',
            field=models.IntegerField(null=True),
        ),
    ]
